version: "3.8"
services:
  php:
    container_name: etm_app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/usr/src/app
    restart: on-failure
    env_file:
      - .env.local
    # This statement is used to tell the service that it will have to use the user with uid 1000 and gid 1000 internally.
    # In most cases, the user we use on our local machine is the user with uid 1000 and gid 1000.
    user: 1000:1000
  etm_dbc:
    image: mysql:8.0
    container_name: etm_dbc
    restart: on-failure

    volumes:
      - etm_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - .env.local
    ports:
      - "5501:3306"

  nginx:
    image: nginx:1.15.3-alpine
    container_name: etm_web
    restart: on-failure
    volumes:
      - "./public/:/usr/src/app"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - php
    ports:
      - 8007:80

  # php_test:
  #   container_name: etm_test
  #   build:
  #     context: .
  #     dockerfile: docker/php/Dockerfile
  #   volumes:
  #     - ./:/usr/src/app
  #   restart: on-failure
  #   env_file:
  #     - .env.test
  #   # This statement is used to tell the service that it will have to use the user with uid 1000 and gid 1000 internally.
  #   # In most cases, the user we use on our local machine is the user with uid 1000 and gid 1000.
  #   user: 1000:1000
  # etm_test_dbc:
  #   image: mysql:8.0
  #   container_name: etm_test_dbc
  #   restart: on-failure

  #   volumes:
  #     - etm_test_db:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #   env_file:
  #     - .env.test
  #   ports:
  #     - "5596:3306"

  # nginx_test:
  #   image: nginx:1.15.3-alpine
  #   container_name: etm_test_web
  #   restart: on-failure
  #   volumes:
  #     - "./public/:/usr/src/app"
  #     - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
  #   depends_on:
  #     - php
  #   ports:
  #     - 8096:80

volumes:
  etm_db:
  # etm_test_db:
